TABLES = {
    "smes": {
        "id": "uuid default gen_random_uuid() primary key",
        "email": "text unique not null",
        "password_hash": "text not null",
        "business_name": "text not null",
        "phone": "text not null",
        "created_at": "timestamptz default now()",
    },
    "subscription_plans": {
        "id": "uuid default gen_random_uuid() primary key",
        "sme_id": "uuid references smes(id) not null",
        "name": "text not null",
        "description": "text",
        "amount": "integer not null",
        "currency": "text default 'XAF'",
        "interval_days": "integer default 30",
        "is_active": "boolean default true",
        "created_at": "timestamptz default now()",
    },
    "subscribers": {
        "id": "uuid default gen_random_uuid() primary key",
        "sme_id": "uuid references smes(id) not null",
        "plan_id": "uuid references subscription_plans(id) not null",
        "name": "text not null",
        "phone": "text not null",
        "is_active": "boolean default true",
        "created_at": "timestamptz default now()",
    },
    "payment_cycles": {
        "id": "uuid default gen_random_uuid() primary key",
        "subscriber_id": "uuid references subscribers(id) not null",
        "plan_id": "uuid references subscription_plans(id) not null",
        "amount": "integer not null",
        "currency": "text default 'XAF'",
        "due_date": "date not null",
        "status": "text default 'pending'",
        "retry_count": "integer default 0",
        "last_attempt_at": "timestamptz",
        "created_at": "timestamptz default now()",
    },
    "transactions": {
        "id": "uuid default gen_random_uuid() primary key",
        "sme_id": "uuid references smes(id) not null",
        "cycle_id": "uuid references payment_cycles(id)",
        "subscriber_id": "uuid references subscribers(id) not null",
        "plan_id": "uuid references subscription_plans(id)",
        "pawapay_deposit_id": "text",
        "amount": "integer not null",
        "currency": "text default 'XAF'",
        "provider": "text",
        "status": "text not null default 'pending'",
        "pawapay_status": "text",
        "error_message": "text",
        "created_at": "timestamptz default now()",
        "updated_at": "timestamptz default now()",
    },
    "webhook_logs": {
        "id": "uuid default gen_random_uuid() primary key",
        "pawapay_event_id": "text unique",
        "deposit_id": "text",
        "event_type": "text",
        "status": "text",
        "raw_body": "jsonb",
        "received_at": "timestamptz default now()",
        "processed": "boolean default false",
    },
    "user_preferences": {
        "id": "uuid default gen_random_uuid() primary key",
        "sme_id": "uuid references smes(id) unique not null",
        "business_type": "text default 'solo'",
        "use_case": "text default 'subscriptions'",
        "onboarding_complete": "boolean default false",
        "created_at": "timestamptz default now()",
    },
    "products": {
        "id": "uuid default gen_random_uuid() primary key",
        "sme_id": "uuid references smes(id) not null",
        "name": "text not null",
        "description": "text",
        "price": "integer not null",
        "currency": "text default 'XAF'",
        "is_active": "boolean default true",
        "created_at": "timestamptz default now()",
    },
    "pos_sales": {
        "id": "uuid default gen_random_uuid() primary key",
        "sme_id": "uuid references smes(id) not null",
        "customer_name": "text",
        "customer_phone": "text",
        "total_amount": "integer not null",
        "currency": "text default 'XAF'",
        "payment_method": "text default 'momo'",
        "payment_status": "text default 'pending'",
        "pawapay_deposit_id": "text",
        "receipt_number": "text",
        "created_at": "timestamptz default now()",
    },
    "pos_sale_items": {
        "id": "uuid default gen_random_uuid() primary key",
        "sale_id": "uuid references pos_sales(id) not null",
        "product_id": "uuid references products(id) not null",
        "product_name": "text not null",
        "quantity": "integer not null",
        "unit_price": "integer not null",
        "subtotal": "integer not null",
    },
}
